# Generated by Django 3.1.5 on 2021-01-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0005_auto_20210122_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visitcount',
            field=models.IntegerField(default=0, verbose_name='تعداد بازید'),
        ),
    ]
