# Generated by Django 3.1.5 on 2021-01-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_product_visitcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='visitcount',
            new_name='visit_count',
        ),
    ]
