# Generated by Django 3.1.5 on 2021-01-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0004_sitesettings_logo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='logo_image',
            new_name='logo',
        ),
    ]
