# Generated by Django 3.1.5 on 2021-01-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0005_auto_20210123_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='logo',
            new_name='logo_image',
        ),
    ]
