# Generated by Django 3.2 on 2021-04-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0002_auto_20210121_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silders',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
